jobs:
  - job: 'build_and_publish'
    displayName: 'build & publish packages'
    steps:
      - checkout: self
        persistCredentials: true

      - task: NodeTool@0
        inputs:
          versionSpec: '16.x' 

      - script: |
          node --version
          npm --version
          npm ci --legacy-peer-deps
        displayName: Install NPM packages
          
      - script: npm version minor
        displayName: "bump version"

      - script: npm run prepublish
        displayName: 'test and build lib'

      - script: npm publish
        displayName: 'publish'
