jobs:
  - job: 'build_and_publish'
    displayName: 'build & publish packages'
    steps:
      - checkout: self
        persistCredentials: true

      - task: NodeTool@0
        inputs:
          versionSpec: '16.x' 

      - script: |
          node --version
          npm --version
          npm ci --legacy-peer-deps
        displayName: Install NPM packages
          
      - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
          - script: |
              git config user.email "release@inimco.com"
              git config user.name "Release bot"
            displayName: "set git config"

          - script: npm version minor
            displayName: "bump version"

          - task: Npm@1
            inputs:
              command: publish
              publishRegistry: useFeed
              publishFeed: Facts/facts
