jobs:
  - job: 'build_and_publish'
    displayName: 'build & publish packages'
    steps:
      - checkout: self
        persistCredentials: true

      - task: NodeTool@0
        inputs:
          versionSpec: '16.x' 

      - script: |
          node --version
          npm --version
          npm ci --legacy-peer-deps
        displayName: Install NPM packages
          
      - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
          - script: |
              git config user.email "release@inimco.com"
              git config user.name "Release bot"
            displayName: "set git config"

          - script: npm version minor
            displayName: "bump version"

          - pwsh: |
              git add package.json
              git add package-lock.json
              git commit -m "chore: release v${{parameters.releaseVersion}} [skip ci]" --no-verify
              git push origin HEAD:$(Build.SourceBranch)
            displayName: "Commit changes to Git repo"
            env: { GH_TOKEN: $(System.AccessToken) }
            workingDirectory: ${{ parameters.workingDir }}

          - task: Npm@1
            displayName: "publish artifact"
            inputs:
              command: publish
              publishRegistry: useFeed
              publishFeed: Facts/facts
