trigger:
  batch: true
  branches:
    include:
      - master
pool:
  vmImage: 'ubuntu-latest'
  
stages:
  - stage: 'build'
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'build & publish packages'
    jobs:
      - template: 'templates/build-and-publish.yml'